version: "3.9"

services:
  php-apache:
    build: './build/php'
    ports:
      - "8888:80"
    volumes:
      - ./www:/var/www/html
    container_name: php-apache

  mysql:
    build: './build/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: thoms
      MYSQL_DATABASE: thoms
      MYSQL_USER: thoms
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: thoms
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mysql
    container_name: phpmyadmin
